using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;
using UnityEngine;
using TMPro;
using UnityEngine.SceneManagement;

public class StartScreen : MonoBehaviour
{
    [SerializeField] private GameObject credits;
    [SerializeField] private TMP_Text creditText;
    [SerializeField] private RawImage bg;
    private bool updateSize = true;
    private bool textChanging;

    private void Start() {
        StartCoroutine(fadeOut());
    }

    private void Update() {
        if (updateSize) {
            RectTransform bgRectTransform = bg.transform.gameObject.GetComponent<RectTransform>();
            bgRectTransform.sizeDelta = new Vector2(Screen.width, Screen.height);
        }
    }

    public IEnumerator fadeOut() {
        float time = 0;
        while (time < 1f) {
            creditText.color = new Color(1.0f, 1.0f, 1.0f, (time/1f));
            time += Time.deltaTime;
            yield return null;
        }
        yield return new WaitForSeconds(1f);
        time = 0;
        bool textChanged = false;
        while (time < 1.25f) {
            if (!textChanged) {
                textChanged = true;
                yield return StartCoroutine(ChangeText());
            }
            time += Time.deltaTime;
            yield return null;
        }
        time = 0;
        while (time < 1f) {
            creditText.color = new Color(1.0f, 1.0f, 1.0f, 1-(time/1));
            bg.color= new Color(1.0f, 1.0f, 1.0f, 1-(time/1));
            time += Time.deltaTime;
            yield return null;
        }
        creditText.color = new Color(1.0f, 1.0f, 1.0f, 0);
        bg.color= new Color(1.0f, 1.0f, 1.0f, 0);
        creditText.transform.gameObject.SetActive(false);
        Destroy(bg.transform.gameObject);
        updateSize = false;
        
        yield break;
    }

    public IEnumerator ChangeText() {
        RetroDither.isStartScreen = true;
        string startText = creditText.text;
        string targetText = "Generated by The Model";

        for (int i = startText.Length; i >= 0; i -= UnityEngine.Random.Range(1, 5)) {
            creditText.text = startText.Substring(0, Mathf.Max(i, 0));
            yield return new WaitForSeconds(Random.Range(0, 0.1f));
        }
        creditText.text = "";
        yield return new WaitForSeconds(Random.Range(0, 0.1f));
        for (int i = 0; i <= targetText.Length; i += UnityEngine.Random.Range(1, 5)) {
            creditText.text = targetText.Substring(0, Mathf.Min(i, targetText.Length));
            yield return new WaitForSeconds(Random.Range(0, 0.1f));
        }
        creditText.text = targetText;
        yield return new WaitForSeconds(.25f);
        RetroDither.isStartScreen = false;
        yield break;
    }
    public void StartGame()
    {
        SceneManager.LoadScene("mainScene", LoadSceneMode.Single);
    }

    public void OpenCredits() 
    {
        credits.SetActive(true);
    }

    public void CloseCredits() 
    {
        credits.SetActive(false);
    }

}
