name: Capsule Clash Deploy
on:
  repository_dispatch:
    types: [build triggered]

jobs:
  process-dispatch:
    runs-on: self-hosted
    steps:
      - name: Deploy Client
        run: |
          echo "Status: ${{ github.event.client_payload.status }}"
          echo "Source: ${{ github.event.client_payload.triggered_by }}"
