name: Runner Test
on: workflow_dispatch

jobs:
  hello:
    runs-on: [self-hosted, unity-windows]
    defaults:
      run:
        shell: powershell
    steps:
      - run: Write-Host "runner is alive"
      - run: Get-ComputerInfo | Select-Object CsName, OsName
